_wandb:
    value:
        cli_version: 0.19.10
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 77
                - 103
                - 105
                - 106
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 77
                - 103
                - 105
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.9.21
            "5": 0.19.10
            "6": 4.41.0
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
data:
    value:
        accum_grads: 2
        batch_size: 4
        data_dir: C:\\Users\\shan2\\Documents\\ETH\\MA4\\3DV\\GitHub\\3D-Vision\\DeepLSD\\notebooks\\data
        edge_sample_size:
            - 32
            - 24
        h5_path: C:\\Users\\shan2\\Documents\\ETH\\MA4\\3DV\\GitHub\\3D-Vision\\DeepLSD\\notebooks\\line.data.h5
        json_dir: C:\\Users\\shan2\\Documents\\ETH\\MA4\\3DV\\GitHub\\3D-Vision\\DeepLSD\\notebooks\\data\\json_output
        k_nn: 7
        method: sample
        num_workers: 2
        precompute_dir: /work/scratch/maurdu/data/graph_data/
        roi_output_size:
            - 64
            - 32
        train_split: 0.8
        use_precomputed: false
        val_split: 0.1
model:
    value:
        act: relu
        dropout: 0.1
        edge_downsample_dim: 20
        geom_channels: 6
        hidden_channels: 128
        hidden_channels_cnn: 64
        in_channels: 128
        in_channels_DeepLSD: 1280
        jk_layer: cat
        load_model_path: /home/maurdu/3D-Vision/DeepLSD/notebooks/lightning_tools/lightning_logs/lightning_project/phrkjdq6/checkpoints/best-model-epoch=41-val_combined_auc_epoch=0.9618.ckpt
        mlp_dropout: 0.1
        num_layers: 6
        only_linear: true
        out_channels: 128
        skip_init: "False"
        v2: true
training:
    value:
        accelerator: auto
        devices: auto
        early_stopping_patience: 20
        edge_loss_w: 1
        epochs: 80
        experiment_name: Attention_Edge_Sampler
        learning_rate: 0.0005
        log_dir: lightning_logs
        monitor_metric: val_combined_auc_epoch
        monitor_mode: max
        node_loss_w: 1
        seed: 42
        threshold_structural: 0.5
