_wandb:
    value:
        cli_version: 0.19.10
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 77
                - 103
                - 105
                - 106
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 77
                - 103
                - 105
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.9.21
            "5": 0.19.10
            "6": 4.41.0
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
act:
    value: relu
data:
    value:
        batch_size: 1
        data_dir: C:\\Users\\shan2\\Documents\\ETH\\MA4\\3DV\\GitHub\\3D-Vision\\DeepLSD\\notebooks\\data
        edge_sample_size:
            - 32
            - 24
        h5_path: /mnt/c/Users/shan2/Documents/ETH/MA4/3DV/GitHub/3D-Vision/DeepLSD/notebooks/lines_data.h5
        json_dir: C:\\Users\\shan2\\Documents\\ETH\\MA4\\3DV\\GitHub\\3D-Vision\\DeepLSD\\notebooks\\data\\json_output
        k_nn: 7
        method: sample
        num_workers: 0
        precompute_dir: /work/scratch/maurdu/data/graph_data/
        roi_output_size:
            - 64
            - 32
        train_split: 0.8
        use_precomputed: false
        val_split: 0.1
dropout:
    value: 0.1
edge_downsample_dim:
    value: 20
edge_loss_w:
    value: 1
edge_sample_size:
    value:
        - 32
        - 24
geom_channels:
    value: 8
hidden_channels:
    value: 128
hidden_channels_cnn:
    value: 96
in_channels:
    value: 128
in_channels_DeepLSD:
    value: 1280
jk_layer:
    value: cat
learning_rate:
    value: 0.0005
mlp_dropout:
    value: 0.1
model:
    value:
        act: relu
        dropout: 0.1
        edge_downsample_dim: 20
        geom_channels: 8
        hidden_channels: 128
        hidden_channels_cnn: 96
        in_channels: 128
        in_channels_DeepLSD: 1280
        jk_layer: cat
        load_model_path: /home/maurdu/3D-Vision/DeepLSD/notebooks/lightning_tools/lightning_logs/lightning_project/phrkjdq6/checkpoints/best-model-epoch=41-val_combined_auc_epoch=0.9618.ckpt
        mlp_dropout: 0.1
        num_layers: 6
        only_linear: true
        out_channels: 128
        skip_init: "False"
        v2: true
node_loss_w:
    value: 1
num_layers:
    value: 6
out_channels:
    value: 128
roi_align_embedding_shape:
    value:
        - 64
        - 32
skip_init:
    value: "False"
threshold_structural:
    value: 0.5
training:
    value:
        accelerator: auto
        accum_grads: 8
        devices: auto
        early_stopping_patience: 20
        edge_loss_w: 1
        epochs: 80
        experiment_name: Attention_Edge_Sampler
        learning_rate: 0.0005
        log_dir: lightning_logs
        monitor_metric: val_combined_auc_epoch
        monitor_mode: max
        node_loss_w: 1
        precision: 16-mixed
        seed: 42
        threshold_structural: 0.5
v2:
    value: true
